#ifndef _NL_TRACE_H_
#define _NL_TRACE_H_

#ifdef __cplusplus__
extern "C"{
#endif

#define IFLA_ENUM \
	_(IFLA_UNSPEC), \
	_(IFLA_ADDRESS), \
	_(IFLA_BROADCAST), \
	_(IFLA_IFNAME), \
	_(IFLA_MTU), \
	_(IFLA_LINK), \
	_(IFLA_QDISC), \
	_(IFLA_STATS), \
	_(IFLA_COST), \
	_(IFLA_PRIORITY), \
	_(IFLA_MASTER), \
	_(IFLA_WIRELESS), \
	_(IFLA_PROTINFO), \
	_(IFLA_TXQLEN), \
	_(IFLA_MAP), \
	_(IFLA_WEIGHT), \
	_(IFLA_OPERSTATE), \
	_(IFLA_LINKMODE), \
	_(IFLA_LINKINFO), \
	_(IFLA_NET_NS_PID), \
	_(IFLA_IFALIAS), \
	_(IFLA_NUM_VF), \
	_(IFLA_VFINFO_LIST), \
	_(IFLA_STATS64), \
	_(IFLA_VF_PORTS), \
	_(IFLA_PORT_SELF), \
	_(IFLA_AF_SPEC), \
	_(IFLA_GROUP), \
	_(IFLA_NET_NS_FD), \
	_(IFLA_EXT_MASK), \
	_(IFLA_PROMISCUITY), \
	_(IFLA_NUM_TX_QUEUES), \
	_(IFLA_NUM_RX_QUEUES), \
	_(IFLA_CARRIER), \
	_(IFLA_PHYS_PORT_ID), \
	_(IFLA_CARRIER_CHANGES), \
	_(IFLA_PHYS_SWITCH_ID), \
	_(IFLA_LINK_NETNSID), \
	_(IFLA_PHYS_PORT_NAME), \
	_(IFLA_PROTO_DOWN), \
	_(IFLA_GSO_MAX_SEGS), \
	_(IFLA_GSO_MAX_SIZE), \
	_(IFLA_PAD), \
	_(IFLA_XDP), \
	_(IFLA_EVENT), \
	_(IFLA_NEW_NETNSID), \
	_(IFLA_IF_NETNSID), \
	_(IFLA_CARRIER_UP_COUNT), \
	_(IFLA_CARRIER_DOWN_COUNT), \
	_(IFLA_NEW_IFINDEX), \
	_(IFLA_MIN_MTU), \
	_(IFLA_MAX_MTU)

#define FLAGS_ENUM \
    _(NLM_F_REQUEST, 0x01), \
    _(NLM_F_MULTI, 0x02), \
    _(NLM_F_ACK, 0x04), \
    _(NLM_F_ECHO, 0x08), \
    _(NLM_F_DUMP_INTR, 0x10), \
    _(NLM_F_DUMP_FILTERED, 0x20), \
    /* Modifiers to GET request */  \
    _(NLM_F_ROOT, 0x100), \
    _(NLM_F_MATCH, 0x200), \
    _(NLM_F_ATOMIC, 0x400), \
    _(NLM_F_DUMP, 0x300),   \
    _(NLM_F_REPLACE	0x100), \
    /* Modifiers to NEW request */\
    _(NLM_F_EXCL,	0x200), \
    _(NLM_F_CREATE,	0x400), \
    _(NLM_F_APPEND,	0x800), \
    /* Modifiers to DELETE request */\
    _(NLM_F_NONREC,	0x100), \
    /* Flags for ACK message */\
    _(NLM_F_CAPPED,	0x100), \
    _(NLM_F_ACK_TLVS, 0x200)

#define VF_ENUM \
	_(IFLA_VF_UNSPEC),\
	_(IFLA_VF_MAC),\
	_(IFLA_VF_VLAN),\
	_(IFLA_VF_TX_RATE),\
    _(IFLA_VF_SPOOFCHK),\
	_(IFLA_VF_LINK_STATE),\
	_(IFLA_VF_RATE),\
	_(IFLA_VF_RSS_QUERY_EN),\
	_(IFLA_VF_STATS),\
	_(IFLA_VF_TRUST),\
	_(IFLA_VF_IB_NODE_GUID),\
	_(IFLA_VF_IB_PORT_GUID),\
	_(IFLA_VF_VLAN_LIST),\
	_(IFLA_VF_BROADCAST),

#define IPV4_DEVCONF_ENUM \
    _(IPV4_DEVCONF_FORWARDING), \
	_(IPV4_DEVCONF_MC_FORWARDING), \
	_(IPV4_DEVCONF_PROXY_ARP), \
	_(IPV4_DEVCONF_ACCEPT_REDIRECTS), \
	_(IPV4_DEVCONF_SECURE_REDIRECTS), \
	_(IPV4_DEVCONF_SEND_REDIRECTS), \
	_(IPV4_DEVCONF_SHARED_MEDIA), \
	_(IPV4_DEVCONF_RP_FILTER), \
	_(IPV4_DEVCONF_ACCEPT_SOURCE_ROUTE), \
	_(IPV4_DEVCONF_BOOTP_RELAY), \
	_(IPV4_DEVCONF_LOG_MARTIANS), \
	_(IPV4_DEVCONF_TAG), \
	_(IPV4_DEVCONF_ARPFILTER), \
	_(IPV4_DEVCONF_MEDIUM_ID), \
	_(IPV4_DEVCONF_NOXFRM), \
	_(IPV4_DEVCONF_NOPOLICY), \
	_(IPV4_DEVCONF_FORCE_IGMP_VERSION), \
	_(IPV4_DEVCONF_ARP_ANNOUNCE), \
	_(IPV4_DEVCONF_ARP_IGNORE), \
	_(IPV4_DEVCONF_PROMOTE_SECONDARIES), \
	_(IPV4_DEVCONF_ARP_ACCEPT), \
	_(IPV4_DEVCONF_ARP_NOTIFY), \
	_(IPV4_DEVCONF_ACCEPT_LOCAL), \
	_(IPV4_DEVCONF_SRC_VMARK), \
	_(IPV4_DEVCONF_PROXY_ARP_PVLAN), \
	_(IPV4_DEVCONF_ROUTE_LOCALNET), \
	_(IPV4_DEVCONF_IGMPV2_UNSOLICITED_REPORT_INTERVAL), \
	_(IPV4_DEVCONF_IGMPV3_UNSOLICITED_REPORT_INTERVAL), \
	_(IPV4_DEVCONF_IGNORE_ROUTES_WITH_LINKDOWN), \
	_(IPV4_DEVCONF_DROP_UNICAST_IN_L2_MULTICAST), \
	_(IPV4_DEVCONF_DROP_GRATUITOUS_ARP), \
	_(IPV4_DEVCONF_BC_FORWARDING)

#define IPV6_DEVCONF_ENUM \
	_(DEVCONF_FORWARDING), \
	_(DEVCONF_HOPLIMIT), \
	_(DEVCONF_MTU6), \
	_(DEVCONF_ACCEPT_RA), \
	_(DEVCONF_ACCEPT_REDIRECTS), \
	_(DEVCONF_AUTOCONF), \
	_(DEVCONF_DAD_TRANSMITS), \
	_(DEVCONF_RTR_SOLICITS), \
	_(DEVCONF_RTR_SOLICIT_INTERVAL), \
	_(DEVCONF_RTR_SOLICIT_DELAY), \
	_(DEVCONF_USE_TEMPADDR), \
	_(DEVCONF_TEMP_VALID_LFT), \
	_(DEVCONF_TEMP_PREFERED_LFT), \
	_(DEVCONF_REGEN_MAX_RETRY), \
	_(DEVCONF_MAX_DESYNC_FACTOR), \
	_(DEVCONF_MAX_ADDRESSES), \
	_(DEVCONF_FORCE_MLD_VERSION), \
	_(DEVCONF_ACCEPT_RA_DEFRTR), \
	_(DEVCONF_ACCEPT_RA_PINFO), \
	_(DEVCONF_ACCEPT_RA_RTR_PREF), \
	_(DEVCONF_RTR_PROBE_INTERVAL), \
	_(DEVCONF_ACCEPT_RA_RT_INFO_MAX_PLEN), \
	_(DEVCONF_PROXY_NDP), \
	_(DEVCONF_OPTIMISTIC_DAD), \
	_(DEVCONF_ACCEPT_SOURCE_ROUTE), \
	_(DEVCONF_MC_FORWARDING), \
	_(DEVCONF_DISABLE_IPV6), \
	_(DEVCONF_ACCEPT_DAD), \
	_(DEVCONF_FORCE_TLLAO), \
	_(DEVCONF_NDISC_NOTIFY), \
	_(DEVCONF_MLDV1_UNSOLICITED_REPORT_INTERVAL), \
	_(DEVCONF_MLDV2_UNSOLICITED_REPORT_INTERVAL), \
	_(DEVCONF_SUPPRESS_FRAG_NDISC), \
	_(DEVCONF_ACCEPT_RA_FROM_LOCAL), \
	_(DEVCONF_USE_OPTIMISTIC), \
	_(DEVCONF_ACCEPT_RA_MTU), \
	_(DEVCONF_STABLE_SECRET), \
	_(DEVCONF_USE_OIF_ADDRS_ONLY), \
	_(DEVCONF_ACCEPT_RA_MIN_HOP_LIMIT), \
	_(DEVCONF_IGNORE_ROUTES_WITH_LINKDOWN), \
	_(DEVCONF_DROP_UNICAST_IN_L2_MULTICAST), \
	_(DEVCONF_DROP_UNSOLICITED_NA), \
	_(DEVCONF_KEEP_ADDR_ON_DOWN), \
	_(DEVCONF_RTR_SOLICIT_MAX_INTERVAL), \
	_(DEVCONF_SEG6_ENABLED), \
	_(DEVCONF_SEG6_REQUIRE_HMAC), \
	_(DEVCONF_ENHANCED_DAD), \
	_(DEVCONF_ADDR_GEN_MODE), \
	_(DEVCONF_DISABLE_POLICY), \
	_(DEVCONF_ACCEPT_RA_RT_INFO_MIN_PLEN), \
	_(DEVCONF_NDISC_TCLASS), \
	_(DEVCONF_RPL_SEG_ENABLED), \
	_(DEVCONF_RA_DEFRTR_METRIC)

#define IPSTATS_ENUM \
	_(IPSTATS_MIB_NUM),  \
	_(IPSTATS_MIB_INPKTS),  \
	_(IPSTATS_MIB_INOCTETS),  \
	_(IPSTATS_MIB_INDELIVERS), \
	_(IPSTATS_MIB_OUTFORWDATAGRAMS), \
	_(IPSTATS_MIB_OUTPKTS),  \
	_(IPSTATS_MIB_OUTOCTETS), \
	_(IPSTATS_MIB_INHDRERRORS), \
	_(IPSTATS_MIB_INTOOBIGERRORS), \
	_(IPSTATS_MIB_INNOROUTES), \
	_(IPSTATS_MIB_INADDRERRORS), \
	_(IPSTATS_MIB_INUNKNOWNPROTOS), \
	_(IPSTATS_MIB_INTRUNCATEDPKTS),\
	_(IPSTATS_MIB_INDISCARDS), \
	_(IPSTATS_MIB_OUTDISCARDS), \
	_(IPSTATS_MIB_OUTNOROUTES), \
	_(IPSTATS_MIB_REASMTIMEOUT), \
	_(IPSTATS_MIB_REASMREQDS), \
	_(IPSTATS_MIB_REASMOKS), \
	_(IPSTATS_MIB_REASMFAILS),\
	_(IPSTATS_MIB_FRAGOKS),\
	_(IPSTATS_MIB_FRAGFAILS),\
	_(IPSTATS_MIB_FRAGCREATES),\
	_(IPSTATS_MIB_INMCASTPKTS),\
	_(IPSTATS_MIB_OUTMCASTPKTS),\
	_(IPSTATS_MIB_INBCASTPKTS),\
	_(IPSTATS_MIB_OUTBCASTPKTS),\
	_(IPSTATS_MIB_INMCASTOCTETS),\
	_(IPSTATS_MIB_OUTMCASTOCTETS),\
	_(IPSTATS_MIB_INBCASTOCTETS),\
	_(IPSTATS_MIB_OUTBCASTOCTETS),\
	_(IPSTATS_MIB_CSUMERRORS),\
	_(IPSTATS_MIB_NOECTPKTS),\
	_(IPSTATS_MIB_ECT1PKTS),\
	_(IPSTATS_MIB_ECT0PKTS),\
	_(IPSTATS_MIB_CEPKTS),\
	_(IPSTATS_MIB_REASM_OVERLAPS),\
	_(IPSTATS_MIB_TCPOUTOCTETS),\
	_(IPSTATS_MIB_TCPOUTRETRSOCTETS)


#define RTM_TYPE_ENUM \
	_(RTM_NEWLINK, 16), \
	_(RTM_DELLINK, 17), \
	_(RTM_GETLINK, 18), \
	_(RTM_SETLINK, 19), \
	_(RTM_NEWADDR, 20), \
	_(RTM_DELADDR, 21), \
	_(RTM_GETADDR, 22), \
	_(RTM_NEWROUTE, 24), \
	_(RTM_DELROUTE, 25), \
	_(RTM_GETROUTE, 26), \
	_(RTM_NEWNEIGH, 28), \
	_(RTM_DELNEIGH, 29), \
	_(RTM_GETNEIGH, 30), \
	_(RTM_NEWRULE, 32), \
	_(RTM_DELRULE, 33), \
	_(RTM_GETRULE, 34), \
	_(RTM_NEWQDISC, 36), \
	_(RTM_DELQDISC, 37), \
	_(RTM_GETQDISC, 38), \
	_(RTM_NEWTCLASS, 40), \
	_(RTM_DELTCLASS, 41), \
	_(RTM_GETTCLASS, 42), \
	_(RTM_NEWTFILTER, 44), \
	_(RTM_DELTFILTER, 45), \
	_(RTM_GETTFILTER, 46), \
	_(RTM_NEWACTION, 48), \
	_(RTM_DELACTION, 49), \
	_(RTM_GETACTION, 50), \
	_(RTM_NEWPREFIX, 52), \
	_(RTM_GETMULTICAST, 58), \
	_(RTM_GETANYCAST, 62), \
	_(RTM_NEWNEIGHTBL, 64), \
	_(RTM_GETNEIGHTBL, 66), \
	_(RTM_SETNEIGHTBL, 67), \
	_(RTM_NEWNDUSEROPT, 68), \
	_(RTM_NEWADDRLABEL, 72), \
	_(RTM_DELADDRLABEL, 73), \
	_(RTM_GETADDRLABEL, 74), \
	_(RTM_GETDCB, 78), \
	_(RTM_SETDCB, 79), \
	_(RTM_NEWNETCONF, 80), \
	_(RTM_DELNETCONF, 81), \
	_(RTM_GETNETCONF, 82), \
	_(RTM_NEWMDB, 84), \
	_(RTM_DELMDB, 85), \
	_(RTM_GETMDB, 86), \
	_(RTM_NEWNSID, 88), \
	_(RTM_DELNSID, 89),	\
	_(RTM_GETNSID, 90),	\
	_(RTM_NEWSTATS, 92), \
	_(RTM_GETSTATS, 94), \
	_(RTM_NEWCACHEREPORT, 96), \
	_(RTM_NEWCHAIN, 100), \
	_(RTM_DELCHAIN, 101), \
	_(RTM_GETCHAIN, 102), \
	_(RTM_NEWNEXTHOP, 104), \
	_(RTM_DELNEXTHOP, 105), \
	_(RTM_GETNEXTHOP, 106),	\
	_(RTM_NEWLINKPROP, 108), \
	_(RTM_DELLINKPROP, 109), \
	_(RTM_GETLINKPROP, 110), \
	_(RTM_NEWVLAN, 112), \
	_(RTM_DELVLAN, 113), \
	_(RTM_GETVLAN, 114), \
	_(RTM_NEWNEXTHOPBUCKET, 116), \
	_(RTM_DELNEXTHOPBUCKET, 117), \
	_(RTM_GETNEXTHOPBUCKET, 118)

#define ADDR_FAMILY_ENUM \
	_(AF_UNSPEC), \
	_(AF_LOCAL), \
	_(AF_INET), \
	_(AF_AX25), \
	_(AF_IPX), \
	_(AF_APPLETALK), \
	_(AF_NETROM), \
	_(AF_BRIDGE), \
	_(AF_ATMPVC), \
	_(AF_X25), \
	_(AF_INET6), \
	_(AF_ROSE), \
	_(AF_DECnet), \
	_(AF_NETBEUI), \
	_(AF_SECURITY), \
	_(AF_KEY), \
	_(AF_NETLINK), \
	_(AF_PACKET), \
	_(AF_ASH), \
	_(AF_ECONET), \
	_(AF_ATMSVC), \
	_(AF_RDS), \
	_(AF_SNA), \
	_(AF_IRDA), \
	_(AF_PPPOX), \
	_(AF_WANPIPE), \
	_(AF_LLC), \
	_(AF_IB), \
	_(AF_MPLS), \
	_(AF_CAN), \
	_(AF_TIPC), \
	_(AF_BLUETOOTH), \
	_(AF_IUCV), \
	_(AF_RXRPC), \
	_(AF_ISDN), \
	_(AF_PHONET), \
	_(AF_IEEE802154), \
	_(AF_CAIF), \
	_(AF_ALG), \
	_(AF_NFC), \
	_(AF_VSOCK), \
	_(AF_KCM), \
	_(AF_MAX)

#define RTA_ENUM \
	_(RTA_UNSPEC), \
	_(RTA_DST), \
	_(RTA_SRC), \
	_(RTA_IIF), \
	_(RTA_OIF), \
	_(RTA_GATEWAY), \
	_(RTA_PRIORITY), \
	_(RTA_PREFSRC), \
	_(RTA_METRICS), \
	_(RTA_MULTIPATH), \
	_(RTA_PROTOINFO), \
	_(RTA_FLOW), \
	_(RTA_CACHEINFO), \
	_(RTA_SESSION), \
	_(RTA_MP_ALGO), \
	_(RTA_TABLE), \
	_(RTA_MARK), \
	_(RTA_MFC_STATS), \
	_(RTA_VIA), \
	_(RTA_NEWDST), \
	_(RTA_PREF), \
	_(RTA_ENCAP_TYPE), \
	_(RTA_ENCAP), \
	_(RTA_EXPIRES), \
	_(RTA_PAD), \
	_(RTA_UID), \
	_(RTA_TTL_PROPAGATE), \
	_(RTA_IP_PROTO), \
	_(RTA_SPORT), \
	_(RTA_DPORT), \
	_(RTA_NH_ID),

#define BRIDGE_INFO_ENUM \
	_(IFLA_BR_UNSPEC), \
	_(IFLA_BR_FORWARD_DELAY), \
	_(IFLA_BR_HELLO_TIME), \
	_(IFLA_BR_MAX_AGE), \
	_(IFLA_BR_AGEING_TIME), \
	_(IFLA_BR_STP_STATE), \
	_(IFLA_BR_PRIORITY), \
	_(IFLA_BR_VLAN_FILTERING), \
	_(IFLA_BR_VLAN_PROTOCOL), \
	_(IFLA_BR_GROUP_FWD_MASK), \
	_(IFLA_BR_ROOT_ID), \
	_(IFLA_BR_BRIDGE_ID), \
	_(IFLA_BR_ROOT_PORT), \
	_(IFLA_BR_ROOT_PATH_COST), \
	_(IFLA_BR_TOPOLOGY_CHANGE), \
	_(IFLA_BR_TOPOLOGY_CHANGE_DETECTED), \
	_(IFLA_BR_HELLO_TIMER), \
	_(IFLA_BR_TCN_TIMER), \
	_(IFLA_BR_TOPOLOGY_CHANGE_TIMER), \
	_(IFLA_BR_GC_TIMER), \
	_(IFLA_BR_GROUP_ADDR), \
	_(IFLA_BR_FDB_FLUSH), \
	_(IFLA_BR_MCAST_ROUTER), \
	_(IFLA_BR_MCAST_SNOOPING), \
	_(IFLA_BR_MCAST_QUERY_USE_IFADDR), \
	_(IFLA_BR_MCAST_QUERIER), \
	_(IFLA_BR_MCAST_HASH_ELASTICITY), \
	_(IFLA_BR_MCAST_HASH_MAX), \
	_(IFLA_BR_MCAST_LAST_MEMBER_CNT), \
	_(IFLA_BR_MCAST_STARTUP_QUERY_CNT), \
	_(IFLA_BR_MCAST_LAST_MEMBER_INTVL), \
	_(IFLA_BR_MCAST_MEMBERSHIP_INTVL), \
	_(IFLA_BR_MCAST_QUERIER_INTVL), \
	_(IFLA_BR_MCAST_QUERY_INTVL), \
	_(IFLA_BR_MCAST_QUERY_RESPONSE_INTVL), \
	_(IFLA_BR_MCAST_STARTUP_QUERY_INTVL), \
	_(IFLA_BR_NF_CALL_IPTABLES), \
	_(IFLA_BR_NF_CALL_IP6TABLES), \
	_(IFLA_BR_NF_CALL_ARPTABLES), \
	_(IFLA_BR_VLAN_DEFAULT_PVID), \
	_(IFLA_BR_PAD), \
	_(IFLA_BR_VLAN_STATS_ENABLED), \
	_(IFLA_BR_MCAST_STATS_ENABLED), \
	_(IFLA_BR_MCAST_IGMP_VERSION), \
	_(IFLA_BR_MCAST_MLD_VERSION), \
	_(IFLA_BR_VLAN_STATS_PER_PORT), \
	_(IFLA_BR_MULTI_BOOLOPT),

#define FRA_ENUM \
	_(FRA_UNSPEC), \
	_(FRA_DST), \
	_(FRA_SRC), \
	_(FRA_IIFNAME), \
	_(FRA_GOTO), \
	_(FRA_UNUSED2), \
	_(FRA_PRIORITY), \
	_(FRA_UNUSED3), \
	_(FRA_UNUSED4), \
	_(FRA_UNUSED5), \
	_(FRA_FWMARK), \
	_(FRA_FLOW), \
	_(FRA_TUN_ID), \
	_(FRA_SUPPRESS_IFGROUP), \
	_(FRA_SUPPRESS_PREFIXLEN), \
	_(FRA_TABLE), \
	_(FRA_FWMASK), \
	_(FRA_OIFNAME), \
	_(FRA_PAD), \
	_(FRA_L3MDEV), \
	_(FRA_UID_RANGE), \
	_(FRA_PROTOCOL), \
	_(FRA_IP_PROTO), \
	_(FRA_SPORT_RANGE), \
	_(FRA_DPORT_RANGE)

#ifdef __cplusplus__
}
#endif

#endif /*_NL_TRACE_H_*/